const view=document.querySelector('#view');
const modal=document.querySelector('#modal');
const modalContent=document.querySelector('#modalContent');
const modalClose=document.querySelector('#modalClose');
const photoInput=document.querySelector('#photoInput');
const topTitle=document.querySelector('#topTitle');

const savedPhotos=JSON.parse(localStorage.getItem('ipa_beta06_photos')||'[]');
const savedProfile=localStorage.getItem('ipa_beta06_profile')||'client';
const state={route:'today',mode:'during',profile:savedProfile,leadStage:'new',live:false,liveSeconds:0,liveTimer:null,liveViewers:23,reactions:14,photos:savedPhotos,messages:[
 {type:'guide',name:'Renato · Guia',text:'Bom dia, pessoal! Nosso encontro será às 09h15 na entrada principal.',time:'08:45'},
 {type:'other',name:'Juliana',text:'Perfeito! Já estamos a caminho ☀️',time:'08:47'},
 {type:'other',name:'Carlos',text:'Alguém sabe se vai chover à tarde?',time:'08:50'}
]};
const titles={today:'Hoje',trip:'Minha Viagem',explore:'Explorar',community:'Grupo da viagem',memories:'Memórias',prospect:'Planejar viagem'};

setTimeout(()=>document.querySelector('#splash').classList.add('hide'),1800);
if('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js');
function money(n){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n)}
function timeFmt(s){const m=String(Math.floor(s/60)).padStart(2,'0'),sec=String(s%60).padStart(2,'0');return `${m}:${sec}`}
function setProfile(profile){state.profile=profile;localStorage.setItem('ipa_beta06_profile',profile);state.route=profile==='prospect'?'prospect':'today';render()}
function render(){
 topTitle.textContent=titles[state.route]||'Indo por Aí';
 view.innerHTML=routes[state.route]();
 document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route));
 document.body.classList.toggle('hidden-nav',state.profile==='prospect');
 bind(); window.scrollTo({top:0,behavior:'smooth'});
}
function bind(){
 document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{state.route=b.dataset.go;render()});
 document.querySelectorAll('[data-modal]').forEach(b=>b.onclick=()=>showModal(b.dataset.modal));
 document.querySelectorAll('[data-map]').forEach(b=>b.onclick=()=>window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(b.dataset.map),'_blank'));
 document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>setProfile(b.dataset.profile));
 document.querySelectorAll('#liveBtn').forEach(b=>b.onclick=toggleLive);
 document.querySelectorAll('#addPhoto').forEach(b=>b.onclick=()=>photoInput.click());
 document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;state.route='today';toast('Modo alterado');render()});
 const send=document.querySelector('#sendMessage');if(send)send.onclick=sendMessage;
 const surprise=document.querySelector('#surpriseBtn');if(surprise)surprise.onclick=()=>showModal(`<h2>✨ Surpresa perto de você</h2><div class="card"><span class="chip orange">A 180 metros</span><h3>Gelateria Portuense</h3><p>Avaliação 4,9 · combina com seu perfil e com o orçamento do dia.</p><br><button class="btn btn-primary btn-block" data-map="Gelateria Portuense Porto">Ir agora</button></div>`);
 const lead=document.querySelector('#leadForm');if(lead)lead.onsubmit=submitLead;
 const proposal=document.querySelector('#approveProposal');if(proposal)proposal.onclick=()=>{state.leadStage='approved';toast('Planejamento aprovado!');render()};
 document.querySelectorAll('[data-reaction]').forEach(b=>b.onclick=()=>addReaction(b.dataset.reaction));
 const shareLocation=document.querySelector('#shareLocation');if(shareLocation)shareLocation.onclick=()=>toast('Localização compartilhada com o grupo');
 const livePhoto=document.querySelector('#livePhoto');if(livePhoto)livePhoto.onclick=()=>photoInput.click();
 const mic=document.querySelector('#liveMic');if(mic)mic.onclick=()=>{mic.classList.toggle('active');toast(mic.classList.contains('active')?'Microfone ativado':'Microfone silenciado')};
}

document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>{state.route=b.dataset.route;render()});
modalClose.onclick=()=>modal.close();
photoInput.onchange=handlePhotos;
document.querySelector('#profileBtn').onclick=openAdmin;
document.querySelector('#menuBtn').onclick=()=>showModal(`<img src="assets/logo.png" style="width:210px;display:block;margin:auto"><h2>Escolha o cenário de teste</h2><div class="segmented"><button data-profile="prospect">Ainda não sou cliente</button><button data-profile="client">Já sou cliente</button></div><p>Use os dois perfis para testar a jornada comercial e a experiência durante a viagem.</p>`);

const routes={
 prospect:()=>prospectView(),
 today:()=>state.mode==='before'?beforeView():state.mode==='after'?afterView():duringView(),
 trip:()=>tripView(),
 explore:()=>exploreView(),
 community:()=>state.live?liveView():communityView(),
 memories:()=>memoriesView()
};

function prospectView(){
 if(state.leadStage==='sent')return `<section class="card proposal-card"><div class="state-banner"><div><span class="eyebrow">Solicitação recebida</span><h1>Agora é com a gente.</h1><p>Estamos preparando uma proposta personalizada para sua viagem.</p></div><img src="assets/logo.png" alt="Indo por Aí"></div></section><section class="section"><div class="timeline"><div class="timeline-item"><span class="status done">✓</span><div><b>Pedido recebido</b><small>Hoje · 14:20</small></div></div><div class="timeline-item"><span class="status doing">2</span><div><b>Curadoria em andamento</b><small>Voos, hotel e experiências</small></div></div><div class="timeline-item"><span class="status pending">3</span><div><b>Proposta para aprovação</b><small>Previsão: hoje às 18h</small></div></div></div></section><section class="section"><div class="card"><span class="chip orange">Simulação</span><h3>Sua proposta ficou pronta</h3><p>Portugal · 8 dias · 2 pessoas · experiência completa.</p><br><button class="btn btn-primary btn-block" id="approveProposal">Ver e aprovar proposta</button></div></section><section class="section"><button class="btn btn-outline btn-block" data-profile="client">Simular cliente contratado</button></section>`;
 if(state.leadStage==='approved')return `<section class="hero prospect-hero"><img class="hero-logo" src="assets/logo.png" alt="Indo por Aí"><span class="eyebrow">Planejamento aprovado</span><h1>Sua viagem começou antes do embarque.</h1><p>Nossa equipe já pode iniciar as reservas e informar cada passo pelo aplicativo.</p><div class="hero-actions"><button class="btn btn-primary" data-profile="client">Entrar na minha viagem</button></div></section>`;
 return `<section class="hero prospect-hero"><img class="hero-logo" src="assets/logo.png" alt="Indo por Aí"><span class="eyebrow">Ainda não é cliente?</span><h1>Você sonha. A gente organiza.</h1><p>Planejamento, compras, roteiro, concierge e acompanhamento em um só lugar.</p><div class="hero-actions"><button class="btn btn-primary" data-go="prospect-form">Quero planejar minha viagem</button><button class="btn btn-light" data-profile="client">Já sou cliente</button></div></section>
 <section class="section"><div class="section-head"><h2>Como cuidamos da sua viagem</h2></div><div class="service-list"><div class="card service-card"><div class="service-icon">🧭</div><div><b>Planejamento personalizado</b><p>Roteiro feito para seu perfil e orçamento.</p></div><span>›</span></div><div class="card service-card"><div class="service-icon">🛒</div><div><b>Compramos tudo para você</b><p>Passagens, hotel, transfer, seguro e experiências.</p></div><span>›</span></div><div class="card service-card"><div class="service-icon">📲</div><div><b>Acompanhamento passo a passo</b><p>Você acompanha cada cotação, aprovação e reserva.</p></div><span>›</span></div><div class="card service-card"><div class="service-icon">🎧</div><div><b>Concierge durante a viagem</b><p>Suporte humano, grupo, mapa e modo ao vivo.</p></div><span>›</span></div></div></section>
 <section class="section"><div class="card"><span class="eyebrow">Como funciona</span><div class="journey-step"><span class="step-dot">1</span><div><b>Conte seu sonho</b><p>Destino, datas, orçamento e preferências.</p></div></div><div class="journey-step"><span class="step-dot">2</span><div><b>Receba sua proposta</b><p>Opções com preços e próximos passos.</p></div></div><div class="journey-step"><span class="step-dot">3</span><div><b>Aprove e acompanhe</b><p>Nossa equipe compra e informa tudo pelo app.</p></div></div></div></section>
 <section class="section" id="prospect-form"><div class="section-head"><h2>Vamos começar?</h2></div><form id="leadForm" class="card lead-form"><input required name="name" placeholder="Nome completo"><input required type="email" name="email" placeholder="E-mail"><input name="phone" placeholder="WhatsApp"><input required name="destination" placeholder="Para onde você quer viajar?"><input name="date" placeholder="Quando pretende viajar?"><select name="people"><option>Quantas pessoas?</option><option>1 pessoa</option><option>2 pessoas</option><option>3 a 5 pessoas</option><option>6 ou mais</option></select><textarea name="dream" placeholder="Conte um pouco sobre a viagem dos seus sonhos"></textarea><button class="btn btn-primary btn-block" type="submit">Enviar para o Indo por Aí</button></form></section>`;
}
function duringView(){return `<section class="hero"><span class="eyebrow">Porto · Dia 3 de 7</span><h1>Bom dia, Renato! 👋</h1><p>Sua viagem está acontecendo. O próximo momento já está pronto.</p><div class="hero-status"><div class="hero-status-row"><div><small>Viagem ativa</small><h3>Portugal 🇵🇹</h3></div><b>Dia 3 de 7</b></div><div class="progress"><span></span></div><small>8 de 10 itens concluídos · 80%</small></div></section>
 <section class="section"><div class="quick-actions"><button class="quick" data-go="trip">✈️<small>Roteiro</small></button><button class="quick" data-go="explore">🗺️<small>Mapa</small></button><button class="quick" data-go="community">👥<small>Grupo</small></button><button class="quick" id="liveBtn">🔴<small>Ao vivo</small></button><button class="quick" data-modal="<h2>SOS</h2><p>Sua localização e os dados da viagem serão enviados à equipe Indo por Aí.</p><button class='btn btn-dark btn-block'>Enviar SOS</button>">🆘<small>SOS</small></button></div></section>
 ${modeCard()}
 <section class="section"><div class="section-head"><h2>Próxima ação</h2><span class="chip green">Agora</span></div><div class="card action-card"><div class="action-icon">✈️</div><div class="copy"><b>Check-in online disponível</b><p>Faça o check-in da passagem TAP para evitar filas.</p></div><span>›</span></div></section>
 <section class="section"><div class="section-head"><h2>Hoje em Porto</h2><span class="chip">☀️ 24°C</span></div><div class="stat-row"><div class="card mini-stat"><span>📷</span><strong>${12+state.photos.length}</strong><small>Fotos</small></div><div class="card mini-stat"><span>🎥</span><strong>3</strong><small>Vídeos</small></div><div class="card mini-stat"><span>😊</span><strong>8</strong><small>Momentos</small></div></div></section>
 <section class="section"><div class="grid"><button class="card" data-go="community" style="text-align:left"><span class="chip purple">👥 Grupo</span><h3>12 mensagens</h3><p>O guia publicou um novo aviso.</p></button><button class="card" id="liveBtn" style="text-align:left"><span class="chip orange">🔴 Live</span><h3>${state.live?'Você está ao vivo':'Iniciar modo ao vivo'}</h3><p>${state.live?'23 pessoas assistindo agora.':'Fale com o grupo em tempo real.'}</p></button></div></section>`}
function beforeView(){return `<section class="hero before-hero"><span class="eyebrow">Antes da viagem</span><h1>Portugal está chegando. 🇵🇹</h1><p>Faltam 14 dias. A gente cuida dos detalhes e você acompanha tudo.</p><div class="countdown"><div><strong>14</strong><small>Dias</small></div><div><strong>08</strong><small>Horas</small></div><div><strong>34</strong><small>Min</small></div></div></section>${modeCard()}
 <section class="section"><div class="section-head"><h2>Minha mochila</h2><span class="chip green">6 de 9 prontos</span></div><div class="checklist"><div class="check-row"><span class="check done">✓</span><div><b>Passaporte válido</b><small>Conferido pela equipe</small></div><span>Pronto</span></div><div class="check-row"><span class="check done">✓</span><div><b>Passagem emitida</b><small>TAP · voucher disponível</small></div><span>Pronto</span></div><div class="check-row"><span class="check done">✓</span><div><b>Hotel confirmado</b><small>Reserva garantida</small></div><span>Pronto</span></div><div class="check-row"><span class="check doing">!</span><div><b>Check-in online</b><small>Abre em 3 dias</small></div><span>Pendente</span></div><div class="check-row"><span class="check pending">•</span><div><b>Chip internacional</b><small>Aguardando sua aprovação</small></div><span>R$ 150</span></div><div class="check-row"><span class="check pending">•</span><div><b>Baixar mapa offline</b><small>Recomendado para o dia 1</small></div><span>Fazer</span></div></div></section>
 <section class="section"><div class="section-head"><h2>Acompanhamento das compras</h2></div><div class="timeline"><div class="timeline-item"><span class="status done">✓</span><div><b>Passagem emitida</b><small>Valor final aprovado</small></div><strong>R$ 5.290</strong></div><div class="timeline-item"><span class="status done">✓</span><div><b>Hotel confirmado</b><small>Pagamento concluído</small></div><strong>R$ 4.180</strong></div><div class="timeline-item"><span class="status doing">!</span><div><b>Passeio no Douro</b><small>Opção enviada para aprovação</small></div><button class="btn btn-primary">Aprovar</button></div></div></section>`}
function afterView(){return `<section class="card memory-cover"><img src="assets/logo.png" style="width:160px;display:block;margin-bottom:18px"><span class="eyebrow">Depois da viagem</span><h1>Porto virou memória.</h1><p>42 fotos · 8 vídeos · 12 lugares</p><div class="hero-actions"><button class="btn btn-primary" data-go="memories">Abrir álbum</button><button class="btn btn-light">Criar filme</button></div></section>${modeCard()}<section class="section"><div class="grid"><div class="card"><span class="chip green">👣 Pegadas</span><h3>38 km</h3><p>18 lugares visitados.</p></div><div class="card"><span class="chip orange">⭐ Avaliação</span><h3>4,9</h3><p>Sua experiência com o Indo por Aí.</p></div></div></section>`}
function modeCard(){return `<section class="section"><div class="card mode-card"><span class="eyebrow">Simular momento da jornada</span><h2>${state.mode==='before'?'Preparando sua viagem':state.mode==='during'?'Vivendo sua viagem':'Reviva suas melhores memórias'}</h2><div class="mode-switch"><button data-mode="before" class="${state.mode==='before'?'active':''}">Antes</button><button data-mode="during" class="${state.mode==='during'?'active':''}">Durante</button><button data-mode="after" class="${state.mode==='after'?'active':''}">Depois</button></div></div></section>`}
function tripView(){return `<section class="hero" style="background-image:linear-gradient(150deg,rgba(4,50,67,.9),rgba(8,115,127,.54)),url('https://images.unsplash.com/photo-1555881400-69b7c7f00f17?auto=format&fit=crop&w=1200&q=85')"><span class="eyebrow">Minha viagem</span><h1>Porto, Portugal 🇵🇹</h1><p>05 a 20 de agosto · 15 dias / 14 noites</p><div class="hero-actions"><button class="btn btn-light" data-go="explore">Abrir mapa</button><button class="btn btn-primary" data-modal="<h2>Central de documentos</h2><p>Passagens, vouchers, seguro, ingressos e comprovantes ficam organizados aqui.</p>">Documentos</button></div></section><section class="section"><div class="timeline"><div class="timeline-item"><span class="status done">1</span><div><b>09:00 · Torre dos Clérigos</b><small>Visita ao monumento</small></div><span>›</span></div><div class="timeline-item"><span class="status done">2</span><div><b>12:30 · Almoço</b><small>Casa de Pasto da Palmeira</small></div><span>›</span></div><div class="timeline-item"><span class="status doing">3</span><div><b>15:00 · Livraria Lello</b><small>Ingresso disponível no app</small></div><span>›</span></div><div class="timeline-item"><span class="status pending">4</span><div><b>20:00 · Jantar</b><small>Taberna dos Mercadores</small></div><span>›</span></div></div></section>`}
function exploreView(){return `<section class="section" style="margin-top:0"><div class="section-head"><div><span class="eyebrow">Roteiro inteligente</span><h2>Mapa do dia</h2></div><span class="chip">🚶 8,4 km</span></div></section><section class="section"><div class="map-wrap"><div class="map-grid"></div><div class="river"></div><svg class="route-svg" viewBox="0 0 400 500"><path d="M95 90 C120 170, 260 120, 245 215 S145 300, 215 355 S300 390, 280 430" fill="none" stroke="#147ce5" stroke-width="5" stroke-linecap="round" stroke-dasharray="8 10"/></svg><div class="pin p1"><span>1</span></div><div class="pin p2"><span>2</span></div><div class="pin p3"><span>3</span></div><div class="pin p4"><span>4</span></div><button class="map-fab">➤</button><div class="map-card"><div><b>Torre dos Clérigos</b><p>350 m · 5 min caminhando</p></div><button class="btn btn-primary" data-map="Torre dos Clérigos Porto">Ir agora</button></div></div></section>`}
function communityView(){return `<section class="section" style="margin-top:0"><div class="section-head"><div><span class="eyebrow">Portugal 2026 · 28 pessoas</span><h2>Grupo da viagem</h2></div><button id="liveBtn">🔴 Iniciar live</button></div><div class="card"><div class="people"><div class="person"><i>RF</i><small>Renato</small></div><div class="person"><i>MS</i><small>Marina</small></div><div class="person"><i>CS</i><small>Carlos</small></div><div class="person"><i>JS</i><small>Julia</small></div><div class="person"><i>+8</i><small>Mais</small></div></div></div></section><section class="section"><div class="message guide"><b>📢 Aviso do guia</b><br>Amanhã sairemos às 8h30. O ponto de encontro será na recepção do hotel.<small>09:30</small></div><div class="chat">${state.messages.map(m=>`<div class="message ${m.type==='me'?'me':m.type==='guide'?'guide':''}"><b>${m.name}</b><br>${m.text}<small>${m.time}</small></div>`).join('')}</div><div class="composer"><input id="messageInput" placeholder="Digite uma mensagem..."/><button class="btn btn-purple" id="sendMessage">➤</button></div></section>`}
function memoriesView(){return `<section class="card memory-cover"><img src="assets/logo.png" style="width:150px;display:block;margin-bottom:16px"><span class="eyebrow">Porto 2026</span><h1>Suas melhores histórias vivem aqui.</h1><p>42 fotos · 8 vídeos · 12 lugares</p><div class="hero-actions"><button class="btn btn-primary" id="addPhoto">Adicionar fotos</button><button class="btn btn-light">Criar filme</button></div></section><section class="section"><div class="section-head"><h2>Álbum compartilhado</h2><button id="addPhoto">+ Foto</button></div><div class="photo-grid"><div class="photo">🌉<em>Ribeira</em></div><div class="photo">🍷<em>Douro</em></div><div class="photo">📚<em>Lello</em></div>${state.photos.map((src,i)=>`<div class="photo"><img src="${src}" alt="Foto da viagem"><em>Nova ${i+1}</em></div>`).join('')}</div></section>`}
function liveView(){return `<section class="live-stage"><img class="live-video" src="https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=1200&q=85" alt="Simulação de transmissão em Porto"><div class="live-top"><span class="live-badge">● AO VIVO · ${timeFmt(state.liveSeconds)}</span><span>👥 ${state.liveViewers}</span></div><div class="live-comments"><div class="live-comment"><b>João</b> Onde nos encontramos?</div><div class="live-comment"><b>Marina</b> Que lugar lindo! ❤️</div><div class="live-comment"><b>Você</b> Entrada principal, direto ao ponto 1.</div></div><div class="live-reactions" id="liveReactions"></div><div class="live-controls"><button id="livePhoto">📷</button><button id="liveMic">🎙️</button><button class="hang" id="liveBtn">✕</button><button id="shareLocation">📍</button></div></section><section class="section"><div class="live-metrics"><div class="card"><strong>${state.liveViewers}</strong><small>Assistindo</small></div><div class="card"><strong>${state.reactions}</strong><small>Reações</small></div><div class="card"><strong>${state.messages.length}</strong><small>Mensagens</small></div></div><div class="live-actions"><button data-reaction="❤️">❤️ Curtir</button><button data-reaction="👏">👏 Aplaudir</button><button data-reaction="🔥">🔥 Incrível</button></div></section><section class="section"><div class="card"><h3>Simulação do Modo Live</h3><p>O cronômetro, audiência, reações, foto, microfone e localização funcionam localmente para você testar a experiência.</p></div></section>`}
function submitLead(e){e.preventDefault();state.leadStage='sent';toast('Solicitação enviada para a equipe');render()}
function toggleLive(){state.live=!state.live;state.route='community';if(state.live){state.liveSeconds=0;state.liveTimer=setInterval(()=>{state.liveSeconds++;const badge=document.querySelector('.live-badge');if(badge)badge.textContent=`● AO VIVO · ${timeFmt(state.liveSeconds)}`},1000)}else{clearInterval(state.liveTimer);state.liveTimer=null}toast(state.live?'Transmissão iniciada para o grupo':'Transmissão encerrada');render()}
function addReaction(emoji){state.reactions++;const host=document.querySelector('#liveReactions');if(host){const el=document.createElement('div');el.className='reaction-float';el.textContent=emoji;host.appendChild(el);setTimeout(()=>el.remove(),2400)}toast(`${emoji} reação enviada`)}
function sendMessage(){const input=document.querySelector('#messageInput');if(!input||!input.value.trim())return;state.messages.push({type:'me',name:'Você',text:input.value.trim(),time:new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})});render()}
function handlePhotos(e){[...e.target.files].slice(0,8).forEach(file=>{const r=new FileReader();r.onload=()=>{state.photos.push(r.result);localStorage.setItem('ipa_beta06_photos',JSON.stringify(state.photos));state.route='memories';render()};r.readAsDataURL(file)})}
function showModal(html){modalContent.innerHTML=html;modal.showModal();setTimeout(()=>{modalContent.querySelectorAll('[data-map]').forEach(b=>b.onclick=()=>window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(b.dataset.map),'_blank'));modalContent.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>{modal.close();setProfile(b.dataset.profile)})},0)}
function openAdmin(){const services=[['Passagem',4630,5290],['Hotel',3420,4180],['Transfer',205,280],['Seguro',168,220],['Passeios',760,980]];const totalCost=services.reduce((s,x)=>s+x[1],0),totalSale=services.reduce((s,x)=>s+x[2],0);showModal(`<img src="assets/logo.png" style="width:180px;display:block;margin:auto"><h2>Painel de gestão</h2><div class="grid"><div class="card"><span class="eyebrow">Faturamento</span><h3>${money(82450)}</h3><p>+18% no mês</p></div><div class="card"><span class="eyebrow">Margem média</span><h3>${(((totalSale-totalCost)/totalSale)*100).toFixed(1)}%</h3><p>Lucro protegido</p></div></div><h3>Margem por serviço</h3><table class="admin-table"><tr><th>Serviço</th><th>Custo</th><th>Venda</th><th>Margem</th></tr>${services.map(x=>`<tr><td>${x[0]}</td><td>${money(x[1])}</td><td>${money(x[2])}</td><td class="margin">${(((x[2]-x[1])/x[2])*100).toFixed(1)}%</td></tr>`).join('')}</table>`)}
function toast(msg){const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.appendChild(el);setTimeout(()=>el.remove(),2200)}
render();
